### ISSUE TITLE
转存不了

### ISSUE THREAD

**Issue by yeziyela** [Spazzlo/folderclone#106]
大佬你好 我填写了团队盘的id并且把转存机器人添加进团队盘了，把需要转存的文件也填加到了我的云盘，用了新版的multifolderclone
![QQ截图20200313170130](https://user-images.githubusercontent.com/36954557/76606175-c4afd900-654c-11ea-86ed-4a57767804e5.png)

**Comment by sayainchina** [comment]
退出mm状态，直接在目录下运行那个指令

**Comment by Spazzlo** [comment]
五毛党
