### ISSUE TITLE
How to remove multiple SA from Shared Drive

### ISSUE THREAD

**Issue by Leonyan938** [Spazzlo/folderclone#120]
I used to see 'remove.py' to remove all unneeded SA from Shared Drive super easily. However I can't find it anymore. Just wondering is there a new way to remove SA? Or if I can download remove.py somewhere?

Thanks!

**Comment by roshanconnor123** [comment]
> I used to see 'remove.py' to remove all unneeded SA from Shared Drive super easily. However I can't find it anymore. Just wondering is there a new way to remove SA? Or if I can download remove.py somewhere?
> 
> Thanks!

multimanager remove tdid prefixofsas

**Comment by Leonyan938** [comment]
> > I used to see 'remove.py' to remove all unneeded SA from Shared Drive super easily. However I can't find it anymore. Just wondering is there a new way to remove SA? Or if I can download remove.py somewhere?
> > Thanks!
> 
> multimanager remove tdid prefixofsas

Could you please give me an example of what command I can use? 
Like if my TDID is 0ABDccdD323421PVa3A, and MFC is prefixofsas, then I use command "remove --drive-id 0ABDccdD323421PVa3A --prefix MFC" ?

<img width="526" alt="image" src="https://user-images.githubusercontent.com/3710665/80271345-f8585400-86f1-11ea-951c-dab528b0f6d9.png">

**Comment by NiNiyas** [comment]
multimanager remove 0ABDccdD323421PVa3A prefix mfc-- (To remove users starting with mfc--)

**Comment by Leonyan938** [comment]
Got it! Thanks a million!

**Comment by roshanconnor123** [comment]
> Got it! Thanks a million!

I see that you got it worked
Wonderful !
