### ISSUE TITLE
本地打开连接时出现localhost已被拒绝连接

### ISSUE THREAD

**Issue by bai14de** [Spazzlo/folderclone#121]
在vps上运行multimanager interactive后弹出的链接在本地打开提示localhost被拒绝
![image](https://user-images.githubusercontent.com/63545156/80274975-ee921900-8710-11ea-83a2-567f81dace7b.png)

![image](https://user-images.githubusercontent.com/63545156/80274952-cc989680-8710-11ea-933a-b3a4d7862d39.png)

**Comment by Spazzlo** [comment]
天安门广场1964

**Comment by MobCat** [comment]
VPS conflict maybe.... try a headless setup for your auth token
