### ISSUE TITLE
Can't run multimanager interactive

### ISSUE THREAD

**Issue by alviansab** [Spazzlo/folderclone#123]
I downloaded the json file and placed it in the working directory of python. When I run the command "multimanager interactive" it gives me an error saying
 " File "<stdin>", line 1
    multimanager interactive
                 ^
SyntaxError: invalid syntax"
 Please help

**Comment by NiNiyas** [comment]
Hey. Try this: Create a new folder and move the json file. Open cmd and cd to that new folder. Then try multimanager interactive. Make sure python is updated.

**Comment by alviansab** [comment]
I'm using python 3.8 fully updated. I tried out what you told me to and cmd says multimanager is not recognized as an internal or external command

**Comment by NiNiyas** [comment]
Uninstall using 'pip uninstall folderclone' , reinstall and try again. When installing make sure that you open cmd in admin mode.

**Comment by alviansab** [comment]
I just did exactly that and got the same error. I've attached a picture of the command prompt in case I'm doing something wrong. https://imgur.com/AAcZESH

**Comment by NiNiyas** [comment]
Add 'C:\Python38\Scripts' on PATH and you will be good to go. My Computer-> Properties-> Advanced System Settings -> Environment Variables -> Scroll down and find path and add a semi colon and add the path. Ex. ";C:\Python38\Scripts\"

**Comment by alviansab** [comment]
Thank you so much! It worked!!
