### ISSUE TITLE
'NoneType' Object is not subscriptable

### ISSUE THREAD

**Issue by xd003** [Spazzlo/folderclone#126]
I was cloning and suddenly encountered this error and the cloning was interrupted

**Comment by microtechton** [comment]
@xd003 I am experiencing the same issue and I have switched between CentOS 7.6 and Ubuntu 18.04. I was wondering if you found a possible reason as to why you received this error message because you closed this issue.

**Comment by xd003** [comment]
> @xd003 I am experiencing the same issue and I have switched between CentOS 7.6 and Ubuntu 18.04. I was wondering if you found a possible reason as to why you received this error message because you closed this issue.

yes , actual

**Comment by microtechton** [comment]
May I know how you resolved this issue?
