### ISSUE TITLE
how i can delete folderclone

### ISSUE THREAD

**Issue by HITLER-KILLER** [Spazzlo/folderclone#133]
can anybody please tell me how i can remove folderclone and remove all members from my teamdrive which are added by folderclone
anybody reply as soon as possible

**Comment by matracareg** [comment]
It is useful to know how to use the "help" tool. 
commands:
multimanger interactive
help



[img]https://i.imgur.com/sOEMZ15.jpg[/img]

**Comment by HITLER-KILLER** [comment]
i already tried the help command but i don't know how to use it

**Comment by Gamer4Life2020** [comment]
open multimanger interactive ant at mm> use (remove DRIVE_ID prefix mm)
Like:

mm> remove 0Adfdsf_dfsdfPVA prefix mm
Removing accounts

**Comment by HITLER-KILLER** [comment]
thanks i will try soon
