### ISSUE TITLE
No headpats

### ISSUE THREAD

**Issue by citrus3301** [Spazzlo/folderclone#138]
After I spent 3 days getting it to work it didn't give me hedpats when i finished it, can you make it give me hedpats?

**Comment by DankMemeGuy** [comment]
How old are you? 12?

**Comment by Mz49** [comment]
There’s no plans on having folderclone giving you hedpats, but I can give you one now.

*headpats @citrus3301*

**Comment by citrus3301** [comment]
> How old are you? 12?

You're one to talk with that username
