### ISSUE TITLE
Error list index out of range

### ISSUE THREAD

**Issue by trancanh1102** [Spazzlo/folderclone#144]
I got the list index out of range error, I tried it many times and with lots of different links but I still got that error after running

**Comment by wangx2** [comment]
同样的问题。
![image](https://user-images.githubusercontent.com/16116338/89659947-35dc9800-d903-11ea-96a3-c44d81784b60.png)
现在又出现这样了

**Comment by wangx2** [comment]
![image](https://user-images.githubusercontent.com/16116338/89665088-b3f06d00-d90a-11ea-87bc-433d84bbe14b.png)

**Comment by trancanh1102** [comment]
I am seeing this error continuously and hope someone has the solution to fix it

**Comment by ThatNerdyPikachu** [comment]
no

**Comment by sonhsien** [comment]
I got this error message too. It is happening more and more frequently. It is very much appreciated if the author can fix this.

**Comment by Spazzlo** [comment]
Duplicate of #88
