### ISSUE TITLE
[MFC] sanity check input and output directories before loading drive services

### ISSUE THREAD

**Issue by ljuvtliv** [Spazzlo/folderclone#19]
If input or destination do not exist then multifolderclone silently dies at "BoundedSemaphore with 199 threads" checking both first and erroring out before running would help.

**Comment by Mz49** [comment]
will be added

**Comment by Mz49** [comment]
After a long wait, it's finally been added. Will be pushed in a future update.

**Comment by Mz49** [comment]
Pushed.
