### ISSUE TITLE
Less privileges for SAs

### ISSUE THREAD

**Issue by Mz49** [Spazzlo/folderclone#20]
Currently the readmes say to give owner roles to the SA. But the SA doesn’t need such perms. They can be minimized to at least account creation, please fix.

**Comment by eXhumer** [comment]
....…........... Ok.

**Comment by theghost970** [comment]
> Currently the readmes say to give owner roles to the SA. But the SA doesn’t need such perms. They can be minimized to at least account creation, please fix.

It has to be given the owner role because it's used to add the other SAs the programme created... That's how I understood it.

**Comment by eXhumer** [comment]
Fixed.
