### ISSUE TITLE
[MFC] Some files are not copying

### ISSUE THREAD

**Issue by Accorsi66** [Spazzlo/folderclone#23]
For example a have a folder with 3431 files and copied only 3429 files.

**Comment by Mz49** [comment]
@theghost970 @Accorsi66 Currently, there is yet no available fix, but I can recommend that for best results, use a seedbox. We’re still working on the issue so it can be used on any device.

**Comment by K-E-N-W-A-Y** [comment]
@Mz49 can you implement features like rclone copy or sync. so we can re-run the script for missing files without any problem.

thanks in advance for the amazing script.

**Comment by Mz49** [comment]
@K-E-N-W-A-Y Oh, hey. I recognize you. I'm working on getting many features worked into the scripts. But for now, I think we've solved this issue. Will be pushed in a future update.

**Comment by Mz49** [comment]
Pushed.
@Accorsi66 @K-E-N-W-A-Y Please give it a try! Any feedback is welcome!

**Comment by coolkirankumar** [comment]
After the push, the folderclone is not working.

**Comment by K-E-N-W-A-Y** [comment]
@Mz49 i got few bugs. still, files skipping issue exists also takes longer to rebuild folder hierarchy. create 2-3 duplicates for copied files in the destination.
