### ISSUE TITLE
Files not transferring ownership when migrating to My Drive

### ISSUE THREAD

**Issue by war3zlod3r** [Spazzlo/folderclone#24]
after the clone the SA's have ownership, how do I transfer that to the actual drive owner?

**Comment by Mz49** [comment]
this should be pretty straightforward. as long as it remains in the shared drive, it will be "owned" by the share drive. the SAs do not own anything. To transfer ownership to yourself, simply drag and drop the copied content to your drive.

**Comment by war3zlod3r** [comment]
I did that but the files remained owned by the SA accounts giving me read and edit but not delete rights

**Comment by war3zlod3r** [comment]
Followed your instructions again to test, still results in the same issue after being copied to owners drive ownership is not transferred.

**Comment by Mz49** [comment]
This issue seems to be somewhat prevalent among other issues. I'll look into it.

**Comment by CorgiZack** [comment]
![__poke mon](https://user-images.githubusercontent.com/45191160/62407960-5a7e9100-b586-11e9-80da-203d6c821510.jpg)
![__pokemon](https://user-images.githubusercontent.com/45191160/62407961-610d0880-b586-11e9-874f-b7c89efa0bd1.jpg)

I mostly focused on the Pokemon games for these, but hopefully this is at least useful for archival reasons.

**Comment by Mz49** [comment]
After many tests, we were able to confirm this isn’t an issue with multifolderclone. You’ll have to give Google some time to transfer full ownership.
