### ISSUE TITLE
[MFC] Add check to verify if current file to be copied already exists in destination

### ISSUE THREAD

**Issue by eXhumer** [Spazzlo/folderclone#26]
Title self explanatory.

**Comment by s-zeng** [comment]
We can go unix philosophy on this and hook into [rclone check](https://rclone.org/commands/rclone_check/) for this functionality. If you guys don't mind, I can take a crack at implementing something using this method sometime this weekend.

**Comment by K-E-N-W-A-Y** [comment]
> We can go unix philosophy on this and hook into [rclone check](https://rclone.org/commands/rclone_check/) for this functionality. If you guys don't mind, I can take a crack at implementing something using this method sometime this weekend and submit a PR.

this would be a great feature

**Comment by Spazzlo** [comment]
> We can go unix philosophy on this and hook into [rclone check](https://rclone.org/commands/rclone_check/) for this functionality. If you guys don't mind, I can take a crack at implementing something using this method sometime this weekend and submit a PR.

the problem with using rclone is that it's reeeeeeally slow. mfc is extremely fast, which is it's whole thing

**Comment by Bilibox** [comment]
With the newest updates since it checks for files now it does not create duplicate files (YAY!) but it seems to still create duplicate folders/subdirs

**Comment by krishne35** [comment]
this will be a huge help

**Comment by Mz49** [comment]
This feature has been implemented. Will be pushed in a later update.
