### ISSUE TITLE
[MFC] Verbage on documentation

### ISSUE THREAD

**Issue by CorgiZack** [Spazzlo/folderclone#27]
Steps to add all the SAs to the Shared Drive
Once the previous script is done making all the accounts, open Google Drive and make a new Shared Drive to copy all the files to.
Add the address ~~mentioned by the script~~ as a Manager to the Shared Drive.
Run the following command python3 masshare.py [SDFolderID]. Replace the [SDFolderID] with XXXXXXXXXXXXXXXXXXX. The Folder ID can be obtained from the Shared Drive Folder Link https://drive.google.com/drive/folders/XXXXXXXXXXXXXXXXXXX. This will add all the service accounts to your Shared Drive.

to:

Steps to add all the SAs to the Shared Drive
Once the previous script is done making all the accounts, open Google Drive and make a new Shared Drive to copy all the files to.
Add the address ***from step 8 above*** as a Manager to the Shared Drive.
Run the following command python3 masshare.py [SDFolderID]. Replace the [SDFolderID] with XXXXXXXXXXXXXXXXXXX. The Folder ID can be obtained from the Shared Drive Folder Link https://drive.google.com/drive/folders/XXXXXXXXXXXXXXXXXXX. This will add all the service accounts to your Shared Drive.

**Comment by CorgiZack** [comment]
NOTE: I know that when you run masshare.py, it shows this address information, but the order doesn't currently fit the workflow correctly.

**Comment by Mz49** [comment]
Steps will be arranged to avoid confusion.
