### ISSUE TITLE
Removing SAs after cloning

### ISSUE THREAD

**Issue by Rudo2204** [Spazzlo/folderclone#28]
First of all, this is a godsend tool! It did everything right with great speed. I love it!
Problem for me is: My team drive is limited to 100 members (not exactly sure why, google said the limit is 600) and is now filled with all SAs. I want to remove all the SAs in batch after cloning folders so I can add more "real" members in.

**Comment by Mz49** [comment]
Sure thing! You can use the newly pushed tool, `remove.py`!

**Comment by krishne35** [comment]
Remove.py remove other accounts
