### ISSUE TITLE
Remove.py removing other accounts too

### ISSUE THREAD

**Issue by krishne35** [Spazzlo/folderclone#32]
Remove.py script is removing account other than sa's which is pita when trying to create a backup point for TD's with multiple users :(

**Comment by krishne35** [comment]
Better go with prefix as it will remain same for all sa's

**Comment by Mz49** [comment]
A few options have been added. Will be pushed in a future update.

**Comment by krishne35** [comment]
Thanks 😊

**Comment by Mz49** [comment]
Pushed.
