### ISSUE TITLE
Dropped Files not retrying properly

### ISSUE THREAD

**Issue by SameerkumarP** [Spazzlo/folderclone#37]
After the new push, its just keep building folder hierarchy for infinite time and nothing is  happening
![new one](https://user-images.githubusercontent.com/25511024/64335877-60d6b180-cff9-11e9-9e26-01d9f4db2bd0.png)

After that I tried the old repo and it worked fine for me. (used same source and same destination as i took earlier while trying out new push)
![old one](https://user-images.githubusercontent.com/25511024/64336015-a85d3d80-cff9-11e9-88cb-3c24c058bc1c.png)

Can you tell me whats the problem with new push or where I am doing wrong?

**Comment by eXhumer** [comment]
Can you try again with the latest update to the script?

**Comment by Mz49** [comment]
I'm aware there's a few bugs, I'm doing all I can to fix it up.

**Comment by Mz49** [comment]
I've pushed a new update. Please give it a try.

**Comment by coolkirankumar** [comment]
As you said, I tested new push.
Now the folder hierarchy build is fast.
But another new problem.
Process is still running and keeps repeating same logs. (but changes the no of files) See below.
![keeps repeating](https://user-images.githubusercontent.com/25511024/64473801-fbb1c600-d188-11e9-87b3-e248518006f0.png)

I waited for 2 hours . Process is still running.
I tried old repo and it finished with in 2 minutes.
Any ideas?

**Comment by skorpioneMM** [comment]
> As you said, I tested new push.
> Now the folder hierarchy build is fast.
> But another new problem.
> Process is still running and keeps repeating same logs. (but changes the no of files) See below.
> ![keeps repeating](https://user-images.githubusercontent.com/25511024/64473801-fbb1c600-d188-11e9-87b3-e248518006f0.png)
> 
> ![keeps repeating 2](https://user-images.githubusercontent.com/25511024/64474010-7d0a5800-d18b-11e9-936c-dc776598e370.PNG)
> 
> I waited for 2 hours . Process is still running.
> I tried old repo and it finished in 2 minutes.
> 
> ![keeps repeating 3](https://user-images.githubusercontent.com/25511024/64474056-6adce980-d18c-11e9-99b3-d3f8646af2a5.PNG)
> 
> Any ideas?

Same problem...
![Screenshot_20190907-214325_JuiceSSH](https://user-images.githubusercontent.com/560266/64479523-9a095000-d1b8-11e9-93fc-64ed1c735332.png)

**Comment by Mz49** [comment]
@coolkirankumar @skorpioneMM Strange, I'll look into it, but in the meanwhile, could I ask that you guys try with a fresh set of SAs?

**Comment by skorpioneMM** [comment]
@Mz49, tried with fresh SAs and its working

**Comment by coolkirankumar** [comment]
> @Mz49, tried with fresh SAs and its working

better than ever or still some issues?

**Comment by Accorsi66** [comment]
Getting the same:
![Uploading 2019-09-09_182232.png…]()
This happen after a successful copy

**Comment by skorpioneMM** [comment]
Yes, the latest builds are not working properly, even with new fresh SAs sometimes multifolderclone stucks in "Finishing, Dropped "x" files... Retrying.

**Comment by Mz49** [comment]
I really thought I should have fixed this... Damn... Time for more debugging :(

**Comment by Bilibox** [comment]
On windows dropped files retries for me (Successfully) 

It still creates duplicates though if the files are already there.

**Comment by bodoamat-git** [comment]
try fresh SA account 

creating duplicate files and the folder is empty in part

![U508](https://user-images.githubusercontent.com/54424439/64904319-e0036e00-d6fa-11e9-8714-b90d6210ff32.png)

**Comment by thepchamp** [comment]
Lol guess I having a same problem... @Mz49 Please fix it ASAP, it's so annoying. I appreciate and thank you for your hard work. <3

![Screenshot_3](https://user-images.githubusercontent.com/49122862/64917329-a852ff80-d7a8-11e9-9d94-5bf3fc8af3bc.png)

**Comment by Mz49** [comment]
We’ve done many changes to multifolderclone. A better error handling system has been implemented. And if that fails, you can abort and retry without copying already copied files. All these updates will be pushed at a later time.
