### ISSUE TITLE
Multiple duplicates of a file

### ISSUE THREAD

**Issue by susilkoirala** [Spazzlo/folderclone#38]
There are many duplicates of the same files in destination (ranging from 30 to 35 dupes of a single file). These files themselves were not inside a folder of their own so just bare in the source directory.
![issue1](https://user-images.githubusercontent.com/23744731/64343394-3510f700-d00c-11e9-9522-a22dc1c67368.png)

And on top of that none of the files inside a folder in the source folder were copied. The folders were copied but not the files.

**Comment by Mz49** [comment]
I'm working on the issue.

**Comment by susilkoirala** [comment]
well, thank you for your work ..

**Comment by Mz49** [comment]
@susilkoirala I think we've found the dupe issue. A new one was just pushed. Give it a try!

**Comment by susilkoirala** [comment]
will do .. hope the missing file issue is also solved .. again thank you your work ..
