### ISSUE TITLE
[Sugesstion] Option for stable and beta branch 

### ISSUE THREAD

**Issue by krishne35** [Spazzlo/folderclone#47]
Since new update has some issues it will be really helpfull to have stabe branch and beta branch

**Comment by Mz49** [comment]
We never really did have a stable release. This whole project as a whole is still a beta. It's a "Use at your own risk" kind of thing.

**Comment by Spazzlo** [comment]
smh mz writing off users of his programs how would you feel if rclone devs told you to fuck off

**Comment by Mz49** [comment]
rclone isn't a beta and I'd feel the same way when they told a certain other to fuck off.
