### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by fanditobandacream** [Spazzlo/folderclone#50]
Getting this at the end:

imac:multi$ python3 multifolderclone.py -s "1Yc5hnG99jU1vB2gLdVUZsklPQPJo6z-o" -d "0ABY5TlhgnTm1Uk9PVA"
Copy from 1Yc5hnG99jU1vB2gLdVUZsklPQPJo6z-o to 0ABY5TlhgnTm1Uk9PVA.
View set to tree (2).
Creating Drive Services |################################| 1199/1199
BoundedSemaphore with 1199 threads
root
<HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?supportsAllDrives=true&alt=json returned "File not found: 0ABY5TlhgnTm1Uk9PVA.">
Complete.
Elapsed Time:
00:02:38.70

That PVA is the same folder I used in the previous step. NOTE: the previous step tells me i hit the max users at 500

**Comment by Mz49** [comment]
How many SAs did you use? Keep in mind you can only have a limit of 600 users in a Shared Drive. You can continue to use a Google Group for more members. If you reached the max user limit, half of those SAs probably won't be able to write to the destination directory. Regardless, you are getting a 404. Meaning they can't even read the source directory.

**Comment by eXhumer** [comment]
Closing this. This is not an issue with folderclone.
