### ISSUE TITLE
Too many files lost

### ISSUE THREAD

**Issue by yuritry** [Spazzlo/folderclone#51]
Folderclone is a great job. But when I used it to clone folders from shared folders to group folder, there were too many files lost.

**Comment by Mz49** [comment]
Try with the newly pushed code.

**Comment by eXhumer** [comment]
After extensively testing the new code, I can say that no files are dropped anymore with the latest scripts. Unless, the issue is with latest script, I am going to close this issue.

**Comment by yuritry** [comment]
Great job!
Thank you.
