### ISSUE TITLE
quick setup

### ISSUE THREAD

**Issue by K-E-N-W-A-Y** [Spazzlo/folderclone#53]
quick setup generated SA's for already existing projects i have.

`python multifactory.py --quick-setup 1`

![image](https://user-images.githubusercontent.com/25846872/65872125-87400080-e39d-11e9-9be8-a41c8ad89d03.png)

it's not a big issue but i don't need 300 SAs because my gsuite team drive only support 100 members maximum

![image](https://user-images.githubusercontent.com/25846872/65872531-5f04d180-e39e-11e9-8b56-e27a590ee4bf.png)

![image](https://user-images.githubusercontent.com/25846872/65872509-53190f80-e39e-11e9-9c81-69781ded5992.png)

new update is great. i didn't find any other bugs & duplicate or missing file issues with this 👍

**Comment by eXhumer** [comment]
Use `--new-only` flag.

**Comment by K-E-N-W-A-Y** [comment]
@eXhumer oh i see plz update guide. so others will not face this issue
