### ISSUE TITLE
Unable to authorize application

### ISSUE THREAD

**Issue by Leonyan938** [Spazzlo/folderclone#64]
python3 multifactory.py --quick-setup 1
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=872649056912-apia5abal8an24repvu28kgf8ob1l7tu.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A44921%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fiam&state=8Vx4Pp1XKCGgwluatGRMGyIZg3SeDq&access_type=offline

So I visit above link, but after I click allow, the website redirected to a localhost webpage. 

http://localhost:44921/?state=8Vx4Pp1XKCGgwluatGRMGyIZg3SeDq&code=4/rwGIj9Vt5cq4reCwXpkBLnejvT1Tv8sRJ0ou8vVCf-mT7yhO-7-nXTkLtIwAyEgTW0V6F_UoHZoywd0OxmxUrfI&scope=https://www.googleapis.com/auth/drive%20https://www.googleapis.com/auth/cloud-platform%20https://www.googleapis.com/auth/iam

Don't know where went wrong. Please help

**Comment by Mz49** [comment]
The localhost webpage should tell you that the flow completed and it is safe to close the page. You should be able to return to the command prompt and continue there.
