### ISSUE TITLE
Issue with "python masshare.py -d YYYYYY"

### ISSUE THREAD

**Issue by yuritry** [Spazzlo/folderclone#66]
when I ran "python masshare.py -d YYYYYY",  following error happened:

Traceback (most recent call last):
  File "masshare.py", line 2, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
ModuleNotFoundError: No module named 'google_auth_oauthlib'

**Comment by plato79** [comment]
Just execute `pip install -r requirements.txt`

**Comment by yuritry** [comment]
I created a new shared drive and two projects, added IAM api and google drive api  to both project.  Then I ran following command  and errors accured:

# python serviceaccountfactory.py
Found controllers.
Add more projects:
[project id] [accounts to create]
1. myimagesa 99
2. myimagesb 100
3.
Custom email prefix? myimages
Using 2 projects...
Creating accounts in myimagesa
N/A% (0 of 99) |                                                            | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "serviceaccountfactory.py", line 129, in <module>
    create_service_account_and_dump_key(projects[i]['project_id'],prefix + str(o),acc_dir + "/" + str(gc) + '.json')
  File "serviceaccountfactory.py", line 47, in create_service_account_and_dump_key
    "displayName": service_account_name
  File "C:\Program Files\Python37\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\googleapiclient\http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 429 when requesting https://iam.googleapis.com/v1/projects/myimagesa/serviceAccounts?alt=json returned "Maximum number of service accounts on project reached.". Details: "[{'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '86401s'}]">
100% (99 of 99) |###########################################################| Elapsed Time: 0:00:00 Time:  0:00:00

**Comment by yuritry** [comment]
But there is only one service account in project a, and no service account in project b.

**Comment by plato79** [comment]
This is actually another issue, you should have opened a new one with this.. I think you mean `python3 multifactory.py --quick-setup N`. You set it up as 1 or 2 right ( no need to go over this ). Also check how many projects you really have. If you have created too many projects that would cause problems...

Anyway what I don't understand is the question you first asked was about masshare, so you should have already completed multifactory.py beforehand.. Are you sure you're following the [README](https://github.com/Spazzlo/folderclone/blob/master/README_multifolderclone.md)?

**Comment by yuritry** [comment]
Sorry for that. 
I have resolved this issue.

I setup one new shared drive and two new projects, added IAM api and Google Drive API. When I use 'python3 multifactory.py --quick-setup N', it showed one new API should be enabled. So I just used 'python serviceaccountfactory.py' . Then above issue accrued.  
 I changed to  a new computer, it  was done.

Thank you.

**Comment by Mz49** [comment]
@yuritry Glad you got it resolved.

**Comment by yuritry** [comment]
Thank you.
