### ISSUE TITLE
Getting [Too many projects to create. Max Projects]

### ISSUE THREAD

**Issue by Accorsi66** [Spazzlo/folderclone#68]
I've tried to use the quick setup option via multimanager but I'm getting: "Too many projects to create. Max Projects: 12"
![2019-10-14_112229](https://user-images.githubusercontent.com/51134105/66758701-30462b00-ee75-11e9-9ca1-1ad83042bcf1.png)

**Comment by yuritry** [comment]
you can only have a maximum of 12 projects.

**Comment by Mz49** [comment]
try `list projects` to see what projects you already have.
