### ISSUE TITLE
unabble to figure out template of remove

### ISSUE THREAD

**Issue by krishne35** [Spazzlo/folderclone#77]
multimanager remove 0ADu9pbTi6r4o*****VA prefix mg
local variable 'to_be_removed' referenced before assignment

getting to_be_removed

**Comment by war3zlod3r** [comment]
whats the fix here I'm having the same issue not getting account removed

**Comment by eXhumer** [comment]
Fixed on 0.5.3, update folderclone.

**Comment by K-E-N-W-A-Y** [comment]
same bug for new version. 

folderclone 0.5.3
py 3.7.6

![image](https://user-images.githubusercontent.com/25846872/74211664-efd9ab00-4cb6-11ea-9513-51cf9c5afaf1.png)
