### ISSUE TITLE
Error running multimanager 

### ISSUE THREAD

**Issue by YLaido** [Spazzlo/folderclone#78]
Just installed the package with `pip`.

Traceback (most recent call last):
  File "/usr/local/bin/multimanager", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/folderclonecli/mmparse.py", line 177, in main
    subparsers = parse.add_subparsers(help='Commands',dest='command',required=True)
  File "/usr/lib/python2.7/argparse.py", line 1674, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

**Comment by birosticky** [comment]
I'm having the same issue but with line 1678 in add_subparsers

**Comment by YLaido** [comment]
Anyone has problem adding service accounts can try the `masshare.py` in this repo: https://github.com/Rhilip/AutoRclone

**Comment by armanplex** [comment]
> 
> 
> I'm having the same issue but with line 1678 in add_subparsers
> 
> Edit: using python 3.7 error is fixed.

I have the same problem using python 3.7. How did you fix the problem? Thank you

**Comment by YLaido** [comment]
> > I'm having the same issue but with line 1678 in add_subparsers
> > Edit: using python 3.7 error is fixed.
> 
> I have the same problem using python 3.7. How did you fix the problem? Thank you

You might want to check out another repo in my suggestion above. It has more functionalities and structions. It even got a chat group for you to ask questions.
