### ISSUE TITLE
Debian/DietPi - Multimanager Interactive command not working

### ISSUE THREAD

**Issue by JohnDoe-dev-spec** [Spazzlo/folderclone#80]
Hi,

I am trying to get  folderclone to work on my Debian machine as i'd like to use as small a footprint machine as possible for running FolderClone. I have gotten it to work with Windows 10 no problem, no issues there.

However, on my Debian machine it appears not to be working and failing at the first hurdle.

Screenshot attached below of the error when running multimanager interactive. Credentials.json is in the same directory as well.

![Capture](https://user-images.githubusercontent.com/57029587/67615747-eb50bb80-f7c7-11e9-81b4-a4797e05be74.JPG)

Any help appreciated, thanks.

**Comment by armanplex** [comment]
I have the same problem using python 3.7. I appreciate any help

**Comment by JohnDoe-dev-spec** [comment]
Thanks for clarifying, eXhumer. Might be worthwhile mentioning in the read me or requirements the version of Python that is required, just in case someone else experiences the same issue.
