### ISSUE TITLE
source folder "Source_Folder_ID" cannot be read or is invalid

### ISSUE THREAD

**Issue by aemmadi** [Spazzlo/folderclone#91]
Setup everything on README, but when executed the last command i get the error

`Source folder <my-folder-id> cannot be read or is invalid.`

I see all the service accounts in my destination drive and the credentials that are used are those of the source drive.

**Comment by aemmadi** [comment]
FIX: The source folder needs to be public (Sharing settings)

**Comment by nado0** [comment]
How to do it

**Comment by gcp5678** [comment]
我也是这个问题

**Comment by shangjunimo** [comment]
怎么解决?
